name:                structural-json
version:             0.1.0.0
github:              "githubuser/structural-json"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/structural-json#readme>

dependencies:
- base >= 4.7 && < 5
- recursion-zipper
- aeson
- aeson-extra
- lens
- recursion-schemes
- mtl
- containers
- vty
- text
- free
- vector
- unordered-containers
- aeson-pretty
- bytestring
- comonad
- text-zipper
- scientific
- hashable

default-extensions:
- FlexibleInstances
- FlexibleContexts
- ScopedTypeVariables
- LambdaCase
- ViewPatterns
- TypeApplications
- TypeOperators
- DeriveFunctor
- DeriveTraversable
- DeriveGeneric
- DerivingStrategies
- StandaloneDeriving
- TemplateHaskell
- RankNTypes
- GADTs
- MultiParamTypeClasses

ghc-options:
- -Wall

library:
  source-dirs: src

executables:
  structural-json-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - structural-json

tests:
  structural-json-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - structural-json
